before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yqq bc pure-ftpd
  - sudo groupadd ftp
  - sudo useradd -s /bin/false -d /home/ftp -m -c "ftp test user" -g ftp ftp
  - (echo "McChubbers"; echo "McChubbers") | sudo pure-pw useradd fluffy -u ftp -d /home/ftp
  - sudo pure-pw mkdb
  - echo "no" | sudo tee /etc/pure-ftpd/conf/AutoRename
  - cat /etc/pure-ftpd/conf/AutoRename
  - sudo /etc/init.d/pure-ftpd stop
  - sudo /usr/sbin/pure-ftpd -jl puredb:/etc/pure-ftpd/pureftpd.pdb &
  - mv ./tests/secrets.example.json ./tests/secrets.json

language: node_js

node_js:
  - "0.10"
  - "0.8"

script: jake test --trace
